# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LingvoPal' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks

pod 'Google/SignIn'
pod 'ooVooSDK2', '~>2.0'

end
